### ISSUE TITLE
private key instead of mnemonic?

### ISSUE THREAD

**Issue by colombo-77** [azerpas/uniswap-cli#13]
Hey @azerpas , great tool you have built and I think it is amazingly useful! I am trying to set it up and got a quick question, is there a way to use the private key instead of the mnemonic?

**Comment by azerpas** [comment]
> Hey @azerpas , great tool you have built and I think it is amazingly useful! I am trying to set it up and got a quick question, is there a way to use the private key instead of the mnemonic?

Hey @colombo-77, for now it only accepts a mnemonic/seed phrase type of string. I'll make sure to allow both in the near future 😊

**Comment by azerpas** [comment]
A couple hours flight and voilà: https://github.com/azerpas/uniswap-cli/releases/tag/v0.5.2

Enjoy! @colombo-77

**Comment by colombo-77** [comment]
Hey @azerpas that is magic!!! Super cool, thank you!!! Looking forward to testing rightaway!!!
