### ISSUE TITLE
Error: Failed to quote swap from ADDRESS1 to ADDRESS2. Check that a pool exists for this pair [GOERLI]

### ISSUE THREAD

**Issue by DiMiTriFrog** [azerpas/uniswap-cli#9]
When i create a LP en V3 i can't swap from uniswap-cli.

ADDRES1 is my deploy token
ADDRES2 is a deployed token, is not mine and is not wETH

If I go to uniswap UI i can swap them but if i try to do using the client, i'm giving this message error:

`Error: Failed to quote swap from ADDRESS1 to ADDRESS2. Check that a pool exists for this pair. 

The code I'm using:
`cargo run -- -u https://eth-goerli.public.blastapi.io  -n 5 -a 10000000000000000000000000 -s 28562964560000000000 -i ADDRESS1 -o ADDRESS2 -b 2 -v`

When I'm using the TOKEN is not mine + wETH Goerli is working, because there is a LP with both, but with ADDRESS1 + ADDRESS( I created a pool and on uniswap is working) is not working and my Token + wETH Goerli is no tworing too.

`(Obviously i checked that the Addresses are right). I'm using the Router and Quoter by default on the lib and the LP is on V3.

Some  thoughts about this????

Thank you!

**Comment by DiMiTriFrog** [comment]
It's so weird.. I'm creating the LP using Uniswap UI, and it's look like there isn't a pool creation. But i can swap on Uniswap... I'm so confused right now.

**Comment by DiMiTriFrog** [comment]
@azerpas I think you can help me :)

**Comment by DiMiTriFrog** [comment]
Okey, if we are using ROUTER and QUOTER to swap two tokens, one of these tokens must be paired with WETH. 

To avoid it should use the UniversalRouter, same is using Uniswap DAPP. 

So solved!

**Comment by azerpas** [comment]
> Okey, if we are using ROUTER and QUOTER to swap two tokens, one of these tokens must be paired with WETH.
> 
> To avoid it should use the UniversalRouter, same is using Uniswap DAPP.
> 
> So solved!

Sorry for the late reply!

Effectively it seems that `UniversalRouter` [has become the preferred entrypoint for ERC20 swaps](https://docs.uniswap.org/contracts/v3/reference/deployments). 

At first glance it would require a bit of tweaking to support it but you're very welcome to open a PR @DiMiTriFrog. 😊
